import Control from './Contorl'
import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Egoing Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", { cache: "no-store" })
  const topics = await resp.json()
  console.log('app/layout.js/topics', topics)
  return (
    <html>
      <body>
        <h1>Root Layout</h1>
        <h1><Link href="/">Web</Link></h1>
        <ol>
          <p>다이나믹 라우팅</p>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            )
          })}

        </ol>
        <span style={{ color: "red" }}>Root Layout children</span>
        {children}
        <span style={{ color: "red" }}>Root Layout children</span>
        <Control />
      </body>
    </html>
  )
}
